dbt_demo:
  outputs:
    dev:
      dataset: dbt_netflix_demo
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: service-account
      priority: interactive
      project: spark-project-777
      keyfile: /opt/airlow/credentials.json
      threads: 1
      type: bigquery
  target: dev
